### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by rossird**
A lot of changes. Please review it all. This branch integrates a lot of features. Only feature not implemented is index storing. Need to update the displaying to be nicer. Also need to test a bit.

### CODE REVIEW

**Comment by drakeae** [comment]
It looks fine to me.

**Comment by jromie0924** [comment]
What's the reason for making buttons "final?" Other than that it looks good to me.

**Comment by rossird** [comment]
It won't compile for me otherwise. I have no idea why though.

Ricky Rossi

Sent from my iPhone

On Feb 6, 2015, at 4:12 PM, Jackson Romie <notifications@github.com<mailto:notifications@github.com>> wrote:

What's the reason for making buttons "final?" Other than that it looks good to me.

**Comment by jromie0924** [comment]
Doesn’t bother me, just noticed.

**Comment by badams2527** [comment]
Yeah same issue for me. Everything else looks good though. 

~Brian Adams

**Pull request merged**
